# Homework 03 - Nonstandard Evaluation and Git

## Nonstandard Evaluation

### Question 1
Imagine we have a data frame called `data`, with a `type` column. Which one works and why?\
Function 1:
```
group_and_tally <- function(df, column){
    df %>% group_by({{ column }}) %>% tally();
}
group_and_tally(data, type);
```

Function 2:
```
group_and_tally <- function(df, column){
    df %>% group_by(column) %>% tally();
}
group_and_tally(data, type);
```

Answer: 
Function 1 works in this case because the double curly brackets indicate to call by the name of the column versus by the word "column" as the name of a column. In this case, the column name is "type" and column is just the type of organizer. Function 2 would not work because it indcates to organize and tally by the word column versus type.

## Git
For the questions below, please add the commands you used to complete these steps.

### Question 2
Set up your git repo on your local computer. If you already make a git repo on GitHub, but it isn’t on your local computer - clone it.

```
git clone https://github.com/shrayasandhir/BIO512-Repo-Sandhir.git
```

### Question 3
Set up your SSH key.

Answer: 
in terminal --
```
shrayasandhir@MacBook-Pro-266 ~ % ssh-keygen -t ed25519 -C "shrayasandhir@gmail.com"
```
I pressed enter three times to create this output: 
```
Generating public/private ed25519 key pair.
Enter file in which to save the key (/Users/shrayasandhir/.ssh/id_ed25519): 
Enter passphrase for "/Users/shrayasandhir/.ssh/id_ed25519" (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /Users/shrayasandhir/.ssh/id_ed25519
Your public key has been saved in /Users/shrayasandhir/.ssh/id_ed25519.pub
The key fingerprint is:
SHA256:gi6RE631C4GsI0RA8DPv0ciWcSzIZ8ssQSCBcIUr/h8 shrayasandhir@gmail.com
The key's randomart image is:
+--[ED25519 256]--+
|&=oo.            |
|+*.+ .           |
| .@.O o          |
|o../ %           |
|=.* & + S        |
|.o B o o         |
|  o oE.          |
|   o  .          |
|    ..           |
```

### Question 4
a) Add a HW2 directory to your git repo through the terminal with a HW.md file that says "This is for homework 2."

Answer: 
In terminal --
```
mkdir HW2
echo "This is for homework 2." > HW2/HW.md
git add HW2/HW.md
git commit -m "Add HW2 directory with HW.md file"
git push origin main
```

b) *Add* HW2.md to the staging area. Then, use the command to see which files have been modified, staged for commit, or are untracked. What does it show?
They should copy paste the terminal response after git status, and show that key used the commands below.

Answer:
In terminal -- 
```
shrayasandhir@MacBook-Pro-266 BIO512-Repo-Sandhir % echo "This is for homework 2." > HW2.md
git add HW2.md
git status
```
Output: 
```
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   HW2.md
```

c) Save file changes to the main branch.

Answer: 
In terminal -- 
```
git commit -m "Add HW2.md file"
git push origin main
```

d) Now, edit the HW2.md file to give it a title.

Answer: 
In terminal --
```
echo "# Homework 3 markdown file" > HW2.md
git add HW2.md
git commit -m "Add title to HW2.md"
git push origin main
```

e) Use the command that compares current, unsaved changes to the main branch. What does it say?\
\
```
git diff main
```

Output: nothing

f) Use the command that checks the status of the working directory and the staging area *again*. What does it say?\
\
```
git status
```
Output: 
```
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```
g) Once again, add HW2.md to the staging area and save the file changes to the main branch. Then, get use the command that gives you project history and paste the output in your homework.

```
git add HW2.md
git commit -m "Add HW2.md"
git log
```

Output: 
```
commit 9582ccfb8b635775152aac98e820eb920010e4ad (HEAD -> main, origin/main, origin/HEAD)
Author: shrayasandhir <shrayasandhir@gmail.com>
Date:   Tue Sep 9 10:46:57 2025 -0400

    Add title to HW2.md

commit 19008a4c08b77e1da01ff934e0257a728670ca97
Author: shrayasandhir <shrayasandhir@gmail.com>
Date:   Tue Sep 9 10:43:08 2025 -0400

    Add HW2.md file

commit a66c107444bc339596882a1415a91107f5d688ae
Author: shrayasandhir <shrayasandhir@gmail.com>
Date:   Tue Sep 9 10:29:04 2025 -0400

    Add HW2 directory with HW.md file

commit ba02e09e1675f307127e2bc44e71da732019c5aa
Author: shrayasandhir <ssandhir@unc.edu>
Date:   Tue Sep 9 09:35:58 2025 -0400
```

h) Do some searching... What `git` command will provide you documentation on other commands? Use that command to find documentation on `git log` and `git show`. What does `--since` mean in regards to `git log`? Copy and paste what is written in the documentation.

Answer: 
The git command that provides documentation is 
```
git help <command of interest>
```

```
git help log
```

Output for ---since

```
--since=<date>, --after=<date>
           Show commits more recent than a specific date.
```

## Tidyverse

Note: Please make sure Binder is set up correctly to run this section. You can follow the instructions here: https://github.com/rjenki/BIOS512.

**Please show your code for this section!** Before completing this section, please run the following.

In [1]:
library(tidyverse)
if (!dir.exists("intermediate")) dir.create("intermediate", recursive = TRUE)
if (!exists("mdpre")) mdpre <- function(x) { print(x) }
if (!exists("ggmd"))  ggmd  <- function(p) { print(p) }

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.5.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.1
✔ purrr     1.0.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

### Question 5

Download the patient_names.csv and patient_properties.csv files from Canvas and read them into R. Manually set the date columns to be date variables. Print the first 10 observations of each.

Answer: 
```R
patient_names <- read.csv("patient_names.csv")
patient_properties <- read.csv("patient_properties.csv")
patient_names$BIRTHDATE <- as.Date(patient_names$BIRTHDATE, format = "%Y-%m-%d")
patient_names$DEATHDATE <- as.Date(patient_names$DEATHDATE, format = "%Y-%m-%d")
print(head(patient_names, 10))
print(head(patient_properties, 10))
```

Output after manually setting columns: 
```R
[1] "First 10 observations of patient_names:"
                                     ID BIRTHDATE DEATHDATE      FIRST
1  5605b66b-e92d-c16c-1b83-b8bf7040d51f      <NA>      <NA>  Nikita578
2  6e5ae27c-8038-7988-e2c0-25a103f01bfa      <NA>      <NA>    Zane918
3  8123d076-0886-9007-e956-d5864aa121a7      <NA>      <NA>   Quinn173
4  770518e4-6133-648e-60c9-071eb2f0e2ce      <NA>      <NA>    Abel832
5  f96addf5-81b9-0aab-7855-d208d3d352c5      <NA>      <NA>   Edwin773
6  8e9650d1-788a-78f9-4a28-d08f7f95354a      <NA>      <NA> Frankie174
7  183df435-4190-060e-8f8e-bf63c572b266      <NA>      <NA>  Eilene124
8  720560d4-51da-c38c-ee90-c15935278df1      <NA>      <NA>  Lowell343
9  217851b0-5f47-d376-18b9-0fe4ba77207e      <NA>      <NA>  Adrian111
10 ff331e5c-ab16-e218-f39a-63e11de1ed75      <NA>      <NA>  Eugene421
             LAST      CITY         STATE
1       Erdman779    Quincy Massachusetts
2   Hodkiewicz467    Boston Massachusetts
3    Marquardt819    Quincy Massachusetts
4      Smitham825    Boston Massachusetts
5      Labadie908    Boston Massachusetts
6  Oberbrunner298    Boston Massachusetts
7        Walsh511 Cambridge Massachusetts
8        Price929    Quincy Massachusetts
9      Gleason633    Boston Massachusetts
10   Abernathy524    Boston Massachusetts
[1] "First 10 observations of patient_properties:"
                                     ID  property       value
1  5605b66b-e92d-c16c-1b83-b8bf7040d51f   MARITAL           M
2  5605b66b-e92d-c16c-1b83-b8bf7040d51f      RACE       white
3  5605b66b-e92d-c16c-1b83-b8bf7040d51f ETHNICITY nonhispanic
4  5605b66b-e92d-c16c-1b83-b8bf7040d51f    GENDER           F
5  6e5ae27c-8038-7988-e2c0-25a103f01bfa   MARITAL           M
6  6e5ae27c-8038-7988-e2c0-25a103f01bfa      RACE       white
7  6e5ae27c-8038-7988-e2c0-25a103f01bfa ETHNICITY nonhispanic
8  6e5ae27c-8038-7988-e2c0-25a103f01bfa    GENDER           M
9  8123d076-0886-9007-e956-d5864aa121a7   MARITAL           M
10 8123d076-0886-9007-e956-d5864aa121a7      RACE       white
```

### Question 6
In the data frame pulled from patient_properties, you'll notice that the data is long, not wide. Do a pivot to make the properties their own columns. Print the first 10 observations after you do so.

Answer: 

```R
patient_properties_wide <- patient_properties %>%
  pivot_wider(
    names_from = "property",
    values_from = "value"
  )
print(head(patient_properties_wide, 10))
```
Output:
```R
   ID                                   MARITAL RACE   ETHNICITY   GENDER
   <chr>                                <chr>   <chr>  <chr>       <chr> 
 1 5605b66b-e92d-c16c-1b83-b8bf7040d51f M       white  nonhispanic F     
 2 6e5ae27c-8038-7988-e2c0-25a103f01bfa M       white  nonhispanic M     
 3 8123d076-0886-9007-e956-d5864aa121a7 M       white  nonhispanic M     
 4 770518e4-6133-648e-60c9-071eb2f0e2ce M       white  hispanic    M     
 5 f96addf5-81b9-0aab-7855-d208d3d352c5 M       white  hispanic    M     
 6 8e9650d1-788a-78f9-4a28-d08f7f95354a M       white  hispanic    M     
 7 183df435-4190-060e-8f8e-bf63c572b266 M       asian  nonhispanic F     
 8 720560d4-51da-c38c-ee90-c15935278df1 M       white  nonhispanic M     
 9 217851b0-5f47-d376-18b9-0fe4ba77207e S       black  hispanic    M     
10 ff331e5c-ab16-e218-f39a-63e11de1ed75 M       native hispanic    M 
```

### Question 7
Perform a left join of the names and properties_wide data frames by the ID column and print the first 10 rows.

Answer: 

```R
joined_data <- left_join(patient_names, patient_properties_wide, by = "ID")
print(head(joined_data,10))
```
Output:
```R
                                     ID BIRTHDATE DEATHDATE      FIRST
1  5605b66b-e92d-c16c-1b83-b8bf7040d51f      <NA>      <NA>  Nikita578
2  6e5ae27c-8038-7988-e2c0-25a103f01bfa      <NA>      <NA>    Zane918
3  8123d076-0886-9007-e956-d5864aa121a7      <NA>      <NA>   Quinn173
4  770518e4-6133-648e-60c9-071eb2f0e2ce      <NA>      <NA>    Abel832
5  f96addf5-81b9-0aab-7855-d208d3d352c5      <NA>      <NA>   Edwin773
6  8e9650d1-788a-78f9-4a28-d08f7f95354a      <NA>      <NA> Frankie174
7  183df435-4190-060e-8f8e-bf63c572b266      <NA>      <NA>  Eilene124
8  720560d4-51da-c38c-ee90-c15935278df1      <NA>      <NA>  Lowell343
9  217851b0-5f47-d376-18b9-0fe4ba77207e      <NA>      <NA>  Adrian111
10 ff331e5c-ab16-e218-f39a-63e11de1ed75      <NA>      <NA>  Eugene421
             LAST      CITY         STATE MARITAL   RACE   ETHNICITY GENDER
1       Erdman779    Quincy Massachusetts       M  white nonhispanic      F
2   Hodkiewicz467    Boston Massachusetts       M  white nonhispanic      M
3    Marquardt819    Quincy Massachusetts       M  white nonhispanic      M
4      Smitham825    Boston Massachusetts       M  white    hispanic      M
5      Labadie908    Boston Massachusetts       M  white    hispanic      M
6  Oberbrunner298    Boston Massachusetts       M  white    hispanic      M
7        Walsh511 Cambridge Massachusetts       M  asian nonhispanic      F
8        Price929    Quincy Massachusetts       M  white nonhispanic      M
9      Gleason633    Boston Massachusetts       S  black    hispanic      M
10   Abernathy524    Boston Massachusetts       M native    hispanic      M

## I tried to tibble and have the output be one singular block of text but this is how it printed based on wideness of the data set

### Question 8
Notice something interesting about the names in our data set. Fix the name formatting and print the first 10 observations.

Answer:

```R
joined_data <- joined_data %>%
  mutate(
    FIRST = str_replace_all(FIRST, "[^a-zA-Z]", ""),
    LAST = str_replace_all(LAST, "[^a-zA-Z]", "")
  )
print(head(joined_data, 10))
```

Output: 
```R
                                    ID BIRTHDATE DEATHDATE   FIRST        LAST
1  5605b66b-e92d-c16c-1b83-b8bf7040d51f      <NA>      <NA>  Nikita      Erdman
2  6e5ae27c-8038-7988-e2c0-25a103f01bfa      <NA>      <NA>    Zane  Hodkiewicz
3  8123d076-0886-9007-e956-d5864aa121a7      <NA>      <NA>   Quinn   Marquardt
4  770518e4-6133-648e-60c9-071eb2f0e2ce      <NA>      <NA>    Abel     Smitham
5  f96addf5-81b9-0aab-7855-d208d3d352c5      <NA>      <NA>   Edwin     Labadie
6  8e9650d1-788a-78f9-4a28-d08f7f95354a      <NA>      <NA> Frankie Oberbrunner
7  183df435-4190-060e-8f8e-bf63c572b266      <NA>      <NA>  Eilene       Walsh
8  720560d4-51da-c38c-ee90-c15935278df1      <NA>      <NA>  Lowell       Price
9  217851b0-5f47-d376-18b9-0fe4ba77207e      <NA>      <NA>  Adrian     Gleason
10 ff331e5c-ab16-e218-f39a-63e11de1ed75      <NA>      <NA>  Eugene   Abernathy
        CITY         STATE MARITAL   RACE   ETHNICITY GENDER
1     Quincy Massachusetts       M  white nonhispanic      F
2     Boston Massachusetts       M  white nonhispanic      M
3     Quincy Massachusetts       M  white nonhispanic      M
4     Boston Massachusetts       M  white    hispanic      M
5     Boston Massachusetts       M  white    hispanic      M
6     Boston Massachusetts       M  white    hispanic      M
7  Cambridge Massachusetts       M  asian nonhispanic      F
8     Quincy Massachusetts       M  white nonhispanic      M
9     Boston Massachusetts       S  black    hispanic      M
10    Boston Massachusetts       M native    hispanic      M
```

### Question 9
Using a for statement to loop through the categorical variables (excluding name and ID), print the counts of each unique value in descending order, using the mdpre() function for formatting.

Answer: 

```R
mdpre <- function(x){
  cat("\n```\n")
  print(x)
  cat("\n```\n")
}
categorical_cols <- c("CITY", "STATE", "MARITAL", "RACE", "ETHNICITY", "GENDER")
for (col_name in categorical_cols) {
  
  cat("\n***\n")
  cat(paste("Counts for column:", col_name))
  cat("\n***\n")
  
  counts <- joined_data %>%
    count(!!sym(col_name), sort = TRUE)
  mdpre(counts)
}
```
Output: 
```R
***
Counts for column: CITY
***

```
             CITY   n
1          Boston 541
2          Quincy  80
3       Cambridge  45
4          Revere  42
5         Chelsea  39
6        Weymouth  37
7      Somerville  25
8         Hingham  22
9        Winthrop  22
10      Brookline  17
11        Everett  16
12           Hull  15
13        Medford  13
14      Braintree  10
15       Cohasset  10
16         Malden   8
17       Scituate   8
18         Newton   6
19       Stoneham   5
20 North Scituate   3
21        Reading   2
22        Belmont   1
23      Lynnfield   1
24        Melrose   1
25         Milton   1
26        Norwell   1
27        Waltham   1
28      Watertown   1
29     Winchester   1

```

***
Counts for column: STATE
***

```
          STATE   n
1 Massachusetts 974

```

***
Counts for column: MARITAL
***

```
  MARITAL   n
1       M 782
2       S 189
3    Fine   1
4    male   1
5    <NA>   1

```

***
Counts for column: RACE
***

```
      RACE   n
1    white 680
2    black 163
3    asian  90
4    other  16
5 hawaiian  13
6   native  11
7   asiann   1

```

***
Counts for column: ETHNICITY
***

```
    ETHNICITY   n
1 nonhispanic 781
2    hispanic 190
3  nonhispani   2
4     hispani   1

```

***
Counts for column: GENDER
***

```
  GENDER   n
1      M 493
2      F 478
3 Female   1
4   Male   1
5 female   1

```
```

### Question 10
If you see any weird values, get rid of the ones that don't make sense, and combine the ones that are formatted wrong. Don't forget ot check the dates! Print the new tables for categorical values, and print the date ranges.

### Question 11
Make a histogram of the ages of patients by gender.

### Question 12
Make a scatterplot of birthdate by martial status.